targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
        generate_for:
          include:
            - "**/entities/**.dart"
            - "**/dto/**.dart"
            - "**/swagger_generated_code/**.dart"
      riverpod_generator:
        generate_for:
          include:
            - "**/application/**.dart"
            - "**/**_provider.dart"
            - "lib/l10n/app_localizations.dart"
            - "lib/config/app_router.dart"
        options:
          # Could be changed to "Pod", such that riverpod_generator
          # would generate "countPod" instead of "countProvider"
          # provider_name_suffix: "Provider" # (default)
          # Similar to provider_name_sufix, this is an option for renaming
          # providers with parameters ("families").
          # This takes precedence over provider_name_suffix.
          # provider_family_name_suffix: "Provider" # (default)
      go_router_builder:
        generate_for:
          include:
            - "lib/config/app_router.dart"
          exclude:
            - "lib/features/**.dart"
      chopper_generator:
        options:
          header: "//Generated code"
      swagger_dart_code_generator:
        options:
        # custom configuration options!
          input_folder: "assets/input_folder/"
          output_folder: "lib/features/common/infrastructure/datasources/swagger_generated_code/"
          ignore_headers: true
          separate_models: true
