name: go_money
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  # infrastructure
  riverpod_annotation: ^2.2.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  uuid: ^4.2.1
  #  Domain
  validators: ^3.0.0
  # Other
  go_router: ^12.1.1
  intl: ^0.18.1
  visibility_detector: ^0.4.0+2
  flutter_screenutil: ^5.9.0
  path: ^1.8.3
  path_provider: ^2.0.0
  phosphor_flutter: ^2.0.1
  url_launcher: ^6.2.1
  connectivity_plus: ^5.0.2
  fluttertoast: ^8.2.4
  resource:
    path: packages/resource
  core:
    path: packages/core
  fake_api:
    path: packages/fake_api
  chopper: ^7.0.9
  animate_do: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  freezed: ^2.1.0+1
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.5
  json_serializable: ^6.3.1
  riverpod_lint: ^2.3.2
  custom_lint: ^0.5.4
  go_router_builder: ^2.3.0

flutter:
  uses-material-design: true
  generate: true

scripts: derry.yaml
