name: go_money
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  go_router: ^12.1.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.2.2
  shared_preferences: ^2.0.15
  validators: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  freezed: ^2.1.0+1
  very_good_analysis: ^5.1.0
  build_runner: ^2.2.0
  riverpod_generator: ^2.3.5
  json_serializable: ^6.3.1
  riverpod_lint: ^2.3.2
  custom_lint: ^0.5.4
flutter:
  uses-material-design: true

